### ISSUE TITLE
Liberty-Navbar의 height 문제

### ISSUE THREAD

**Issue by pseol2190** [2DU/openNAMU-Skin-Liberty#6]
스크린샷:
![screenshot](https://user-images.githubusercontent.com/39310079/42379085-a1429cf0-8164-11e8-9224-682da47def90.png)

**Comment by 2DU** [comment]
음 내일 개선하겠습니다

CSS 미디어쿼리 넣으면 해결 될 것 같네요

**Comment by 2DU** [comment]
아 시간이 안 나네요 내일하죠

**Comment by pseol2190** [comment]
~(...)~

**Comment by 2DU** [comment]
수정
